// Ecrit par `cargo test` depuis les commandes de `src-tauri`.
// NE PAS MODIFIER A LA MAIN : la prochaine execution ecrasera tout.
//
// Les enveloppes lisibles, avec leurs commentaires, sont dans `api.ts` -- ici il n'y a que la
// forme exacte de ce que Rust expose.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	etat: () => __TAURI_INVOKE<Etat>("etat"),
	parler: (reference: string, texte: string) => typedError<null, string>(__TAURI_INVOKE("parler", { reference, texte })),
	taire: () => __TAURI_INVOKE<void>("taire"),
	choisirPeripherique: (rang: number) => __TAURI_INVOKE<void>("choisir_peripherique", { rang }),
	forger: (nom: string, fichiers: string[], pitch: number | null, formants: number | null) => typedError<string, string>(__TAURI_INVOKE("forger", { nom, fichiers, pitch, formants })),
	choisirFichiers: () => __TAURI_INVOKE<string[]>("choisir_fichiers"),
	ecrireFiche: (fiche: Fiche, ancien: string) => typedError<Fiche, string>(__TAURI_INVOKE("ecrire_fiche", { fiche, ancien })),
	supprimerFiche: (id: string) => typedError<null, string>(__TAURI_INVOKE("supprimer_fiche", { id })),
	prechauffer: () => typedError<string[], string>(__TAURI_INVOKE("prechauffer")),
	installerPack: () => typedError<string, string>(__TAURI_INVOKE("installer_pack")),
};

/* Types */
export type Etat = {
	pret: boolean,
	fiches: Fiche[],
	packs: Manifeste[],
	panne: string,
	racine: string,
	modeles: string,
	voix: Voix[],
	peripheriques: string[],
	peripherique: number,
};

export type Fiche = {
	id?: string,
	nom: string,
	univers?: string,
	voix?: string,
	repliques?: string[],
};

export type Manifeste = {
	nom: string,
	version?: string,
	description?: string,
	auteur?: string,
	fichiers?: string[],
	installe_le?: string,
};

export type Palier = "clone" | "catalogue";

export type Voix = {
	nom: string,
	reference: string,
	palier: Palier,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

