// Ecrit par `cargo test` depuis les commandes de `src-tauri`.
// NE PAS MODIFIER A LA MAIN : la prochaine execution ecrasera tout.
//
// Les enveloppes lisibles, avec leurs commentaires, sont dans `client.ts` -- ici il n'y a que la
// forme exacte de ce que Rust expose.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	snapshot: () => __TAURI_INVOKE<Snapshot>("snapshot"),
	speak: (reference: string, text: string) => typedError<null, string>(__TAURI_INVOKE("speak", { reference, text })),
	silence: () => __TAURI_INVOKE<void>("silence"),
	speechProgress: () => __TAURI_INVOKE<SpeechProgress>("speech_progress"),
	pause: () => __TAURI_INVOKE<void>("pause"),
	resume: () => __TAURI_INVOKE<void>("resume"),
	selectDevice: (index: number) => __TAURI_INVOKE<void>("select_device", { index }),
	warmUp: () => typedError<string[], string>(__TAURI_INVOKE("warm_up")),
	forgeVoice: (name: string, files: string[], pitch: number | null, formants: number | null) => typedError<string, string>(__TAURI_INVOKE("forge_voice", { name, files, pitch, formants })),
	pickAudioFiles: () => __TAURI_INVOKE<string[]>("pick_audio_files"),
	/**  `previous_id` porte l'identifiant d'avant, pour qu'un renommage ne laisse pas de doublon. */
	writeCharacter: (character: Character, previousId: string) => typedError<Character, string>(__TAURI_INVOKE("write_character", { character, previousId })),
	deleteCharacter: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_character", { id })),
	installPack: () => typedError<string, string>(__TAURI_INVOKE("install_pack")),
	buildPack: (pack: string, chooseFolder: boolean) => typedError<string, string>(__TAURI_INVOKE("build_pack", { pack, chooseFolder })),
	uninstallPack: (pack: string) => typedError<string, string>(__TAURI_INVOKE("uninstall_pack", { pack })),
	packProgress: () => __TAURI_INVOKE<PackProgress>("pack_progress"),
};

/* Types */
export type Character = {
	/**  Deduit du nom, et c'est aussi le nom du fichier. */
	id?: string,
	name: string,
	universe?: string,
	/**
	 *  La reference telle que le moteur l'attend : `judy.wav` pour un clone, `jean` pour une voix
	 *  de catalogue. La fiche ne sait pas lequel des deux c'est, et n'a pas besoin de le savoir.
	 */
	voice?: string,
	/**
	 *  Ce qu'on redit souvent : un prix, une menace, une formule d'accueil. Cliquer la replique
	 *  la fait dire tout de suite -- c'est le geste qui rend l'outil utilisable en pleine partie,
	 *  ou l'on n'a pas le temps de taper.
	 */
	lines?: string[],
};

export type Manifest = {
	name: string,
	version?: string,
	description?: string,
	author?: string,
	/**
	 *  Le script d'extraction, nomme sans son dossier : « starcraft2.rhai ». Vide pour un paquet
	 *  qui porte deja ses voix.
	 */
	recipe?: string,
	/**
	 *  Ce que la recette attend comme jeu, pour le dire a l'utilisateur avant qu'il cherche le
	 *  dossier : « StarCraft II ».
	 */
	game?: string,
	/**
	 *  Le code du jeu tel que `.build.info` le porte -- « sc2 », « fenris » --, qui permet de
	 *  trouver l'installation sans rien demander. Voir `games` : ce n'est PAS le code que rend
	 *  CascLib, qui dit « s2 » pour le meme jeu.
	 */
	product?: string,
	/**  Rempli a l'installation, pas par l'auteur du paquet. */
	files?: string[],
	installed_on?: string,
	/**  Rempli par la fabrication. Vide tant qu'un paquet-recette n'a pas tourne. */
	built_on?: string,
};

export type PackProgress = {
	active: boolean,
	done: number,
	total: number,
	/**  Le fichier ou l'etape en cours, tel quel : la fenetre l'affiche sans l'interpreter. */
	step: string,
	/**
	 *  Ce qui a ete fait jusqu'ici, ligne a ligne. La fenetre le montre pendant l'operation, et
	 *  pas seulement a la fin : sur une fabrication de trois minutes, c'est la seule preuve que
	 *  quelque chose avance.
	 */
	log: string[],
};

export type Snapshot = {
	ready: boolean,
	characters: Character[],
	packs: Manifest[],
	failure: string,
	root: string,
	models: string,
	voices: Voice[],
	devices: string[],
	device: number,
};

export type SpeechProgress = {
	position: number,
	duration: number,
	/**  La duree est connue : la barre peut devenir une vraie proportion. */
	complete: boolean,
	/**  Au moins un echantillon de la replique est passe. Avant, la voix se prepare. */
	audible: boolean,
};

export type Voice = {
	name: string,
	/**  Ce qu'on envoie au moteur : `judy.wav` pour un clone, `jean` pour une voix de catalogue. */
	reference: string,
	kind: VoiceKind,
};

export type VoiceKind = "clone" | "catalog";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

